version: '3.4'

services:
  noobcash_node_2:
    image: "noobcash:latest"
    command: flask run --port 5002
    environment:
      - FLASK_APP=noobcash
      - FLASK_ENV=development
    network_mode: host
    container_name: noobcash_node_2
    restart: always
    volumes:
      - env:/app/env

volumes:
  env:
    driver: local
    name: env
